### ISSUE TITLE
Code for baseline

### ISSUE THREAD

**Issue by sunwell1994** [WiseLabCMU/dart#2]
Thanks for the awesome work and code. I am also interested the signal processing code to generate the results of baselines. Will you include the code in the repo?

**Comment by thetianshuhuang** [comment]
Unfortunately, we don't have a streamlined CFAR implementation; I've cleaned up the matlab script we used, and put it in the [rover repository here](https://github.com/WiseLabCMU/rover/blob/main/docs/cfar.m).

To run the rest of the baseline pipeline, you will need the data processing tools in  `rover` (`cfar`, `map`), and the `simulate` script in this repository (`dart`).
